In [ ]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)
import pandas as pd
import matplotlib.pyplot as plt
# import numpy.linalg as LA
# import tensorflow as tf
# import torch

from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.insert(0,'/content/drive/My Drive/Bot!')
%cd drive/My\ Drive/Bot!/

Mounted at /content/drive
/content/drive/My Drive/Bot!


In [ ]:
# path = 'MarchtoMay_TweetsandNews_fortopicmodeling.csv'
path = 'Processed.csv'
data = pd.read_csv(path)

In [ ]:
df = data[['Handles', 'Content', 'SourceatBot7']]
df = df[:120000]
df

Handles                                            Content  \
0           wittyplease  rt dax_x98 ladi gaga 35m covid-19 relief beyon...   
1            nicktompan  face covid-19 success medit natur 's real heal...   
2           Passion4USA  rt murkymoodr idiot would expect shop tj maxx ...   
3              Garvald2  rt nicolasturgeon stay home protect nhs save live   
4       iammattgonzales  rt dax_x98 ladi gaga 35m covid-19 relief beyon...   
...                 ...                                                ...   
119995         nellstra  rt aspertierra correct https //www.thenation.c...   
119996      LloydMack16  rt stacy_redvirgo reason doubt number death re...   
119997         jetjocko  rt meganmolteni jetjocko import peopl note mod...   
119998      markjuelich  nonprofit empow african american communiti cov...   
119999   ochachachaTea2  wakeupamerica nhk nhkworld_new japantim okabae...   

       SourceatBot7  
0             Human  
1               Bot  
2               Bot  
3             Human  
4             Human  
...             ...  
119995        Human  
119996          Bot  
119997        Human  
119998          Bot  
119999        Human  

[120000 rows x 3 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(df['Content'])
vector = vectorizer.transform(df['Content'])

# debug
print(vector.shape)
print(type(vector))
mydict = vectorizer.vocabulary_
print(len(mydict))
print(dict(list(mydict.items())[0:2]))

(120000, 154011)
<class 'scipy.sparse.csr.csr_matrix'>
154011
{'rt': 122879, 'dax_x98': 53025}


In [ ]:
X = vector
# X = np.asarray(vector)
y = 1*(df['SourceatBot7'] == 'Bot').to_numpy() # Bot = 1, Human = 0
# print(X[0])
# print(X.shape)
print(y)
print(y.shape)
print(np.count_nonzero(y == 0))
print(np.count_nonzero(y == 1))

[0 1 1 ... 0 1 0]
(120000,)
93289
26711


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
def classifier(clf):
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  print('='*80)
  print(clf)
  print('='*80)
  acc = accuracy_score(y_pred, y_test)
  print('Acc:', format(acc,".4f"))
  print('CM:\n', confusion_matrix(y_test, y_pred))
  acc_list.append(acc)
  return acc

In [ ]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.linear_model import RidgeClassifier, Perceptron, PassiveAggressiveClassifier, SGDClassifier, LogisticRegression
from sklearn.svm import LinearSVC

acc_list = []

classifier(BernoulliNB(alpha=.01))
classifier(MultinomialNB(alpha=.01))
classifier(KNeighborsClassifier(n_neighbors=2))
# classifier(KNeighborsClassifier(n_neighbors=10))
classifier(NearestCentroid())
classifier(RidgeClassifier())
classifier(Perceptron())
classifier(PassiveAggressiveClassifier())
classifier(LogisticRegression())
classifier(LinearSVC())
classifier(SGDClassifier())
print(acc_list)

BernoulliNB(alpha=0.01)
Acc: 0.7120
CM:
 [[14242  4481]
 [ 2432  2845]]
MultinomialNB(alpha=0.01)
Acc: 0.7676
CM:
 [[16661  2062]
 [ 3516  1761]]
KNeighborsClassifier(n_neighbors=2)
Acc: 0.7686
CM:
 [[17679  1044]
 [ 4509   768]]
NearestCentroid()
Acc: 0.6395
CM:
 [[12252  6471]
 [ 2180  3097]]
RidgeClassifier()
Acc: 0.7887
CM:
 [[17832   891]
 [ 4181  1096]]
Perceptron()
Acc: 0.7155
CM:
 [[15118  3605]
 [ 3222  2055]]
PassiveAggressiveClassifier()
Acc: 0.7439
CM:
 [[16072  2651]
 [ 3496  1781]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()
Acc: 0.7866
CM:
 [[18166   557]
 [ 4565   712]]
LinearSVC()
Acc: 0.7839
CM:
 [[17538  1185]
 [ 4001  1276]]
SGDClassifier()
Acc: 0.7805
CM:
 [[18706    17]
 [ 5252    25]]
[0.7119583333333334, 0.7675833333333333, 0.768625, 0.6395416666666667, 0.7886666666666666, 0.7155416666666666, 0.743875, 0.7865833333333333, 0.7839166666666667, 0.7804583333333334]
