In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)
import pandas as pd
import matplotlib.pyplot as plt
# import numpy.linalg as LA
# import tensorflow as tf
# import torch

from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.insert(0,'/content/drive/My Drive/Bot!')
%cd drive/My\ Drive/Bot!/

Mounted at /content/drive
/content/drive/My Drive/Bot!


In [2]:
path = 'MarchtoMay_TweetsandNews_fortopicmodeling.csv'
# path = 'Processed.csv'
data = pd.read_csv(path)

In [3]:
df = data[['Handles', 'Content', 'SourceatBot7']]
df = df[:120000]
df

Handles                                            Content  \
0           wittyplease  RT @Dax_x98: Lady Gaga - 35M to COVID-19 relie...   
1            nicktompan  Facing COVID-19 More Successfully: Meditation ...   
2           Passion4USA  RT @MurkyMoodRing: The idiots you would expect...   
3              Garvald2  RT @NicolaSturgeon: STAY HOME. PROTECT THE NHS...   
4       iammattgonzales  RT @Dax_x98: Lady Gaga - 35M to COVID-19 relie...   
...                 ...                                                ...   
119995         nellstra  RT @ASPertierra: Correct. https://www.thenatio...   
119996      LloydMack16  RT @stacy_redvirgo: There is reason to doubt t...   
119997         jetjocko  RT @MeganMolteni: @jetjocko Important for peop...   
119998      markjuelich  This Nonprofit Empowers the African American C...   
119999   ochachachaTea2  #WakeUpAmerica #nhk @NHKWORLD_News @japantimes...   

       SourceatBot7  
0             Human  
1               Bot  
2               Bot  
3             Human  
4             Human  
...             ...  
119995        Human  
119996          Bot  
119997        Human  
119998          Bot  
119999        Human  

[120000 rows x 3 columns]

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(df['Content'])
vector = vectorizer.transform(df['Content'])

# debug
print(vector.shape)
print(type(vector))
mydict = vectorizer.vocabulary_
print(len(mydict))
print(dict(list(mydict.items())[0:2]))

(120000, 157784)
<class 'scipy.sparse.csr.csr_matrix'>
157784
{'rt': 126007, 'dax_x98': 53875}


In [5]:
X = vector
# X = np.asarray(vector)
y = 1*(df['SourceatBot7'] == 'Bot').to_numpy() # Bot = 1, Human = 0
# print(X[0])
# print(X.shape)
print(y)
print(y.shape)
print(np.count_nonzero(y == 0))
print(np.count_nonzero(y == 1))

[0 1 1 ... 0 1 0]
(120000,)
93289
26711


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix
def classifier(clf):
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  print('='*80)
  print(clf)
  print('='*80)
  acc = accuracy_score(y_pred, y_test)
  print('Acc:', format(acc,".4f"))
  print('CM:\n', confusion_matrix(y_test, y_pred))
  acc_list.append(acc)
  return acc

In [8]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.linear_model import RidgeClassifier, Perceptron, PassiveAggressiveClassifier, SGDClassifier, LogisticRegression
from sklearn.svm import LinearSVC

acc_list = []

classifier(BernoulliNB(alpha=.01))
classifier(MultinomialNB(alpha=.01))
classifier(KNeighborsClassifier(n_neighbors=2))
# classifier(KNeighborsClassifier(n_neighbors=10))
classifier(NearestCentroid())
classifier(RidgeClassifier())
classifier(Perceptron())
classifier(PassiveAggressiveClassifier())
classifier(LogisticRegression())
classifier(LinearSVC())
classifier(SGDClassifier())
print(acc_list)

BernoulliNB(alpha=0.01)
Acc: 0.7071
CM:
 [[13993  4730]
 [ 2299  2978]]
MultinomialNB(alpha=0.01)
Acc: 0.7060
CM:
 [[14008  4715]
 [ 2340  2937]]
KNeighborsClassifier(n_neighbors=2)
Acc: 0.7702
CM:
 [[18011   712]
 [ 4803   474]]
NearestCentroid()
Acc: 0.5980
CM:
 [[11516  7207]
 [ 2440  2837]]
RidgeClassifier()
Acc: 0.7631
CM:
 [[16711  2012]
 [ 3673  1604]]
Perceptron()
Acc: 0.7382
CM:
 [[16021  2702]
 [ 3582  1695]]
PassiveAggressiveClassifier()
Acc: 0.7335
CM:
 [[15764  2959]
 [ 3438  1839]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()
Acc: 0.7698
CM:
 [[17059  1664]
 [ 3862  1415]]


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC()
Acc: 0.7495
CM:
 [[16267  2456]
 [ 3556  1721]]
SGDClassifier()
Acc: 0.7855
CM:
 [[17893   830]
 [ 4318   959]]
[0.707125, 0.7060416666666667, 0.7702083333333334, 0.5980416666666667, 0.763125, 0.7381666666666666, 0.7334583333333333, 0.76975, 0.7495, 0.7855]
